# -*- coding: utf-8 -*-

BASE_URL = "https://universaldependencies.org/conll{0}/results-{1}.html"
BROWSER_USER_AGENT = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"

TREEBANK_GROUPS = {"#all-treebanks": ".post-content > pre:nth-child(2)",
                   "#big-treebanks-only": ".post-content > pre:nth-child(5)",
                   "#pud-treebanks-only": ".post-content > pre:nth-child(8)",
                   "#small-treebanks-only": ".post-content > pre:nth-child(11)",
                   "#low-resource-languages-only": ".post-content > pre:nth-child(14)",
                   "#old-treebanks-only": ".post-content > pre:nth-child(17)"}

INDIVIDUAL_TREEBANKS = {"#af_afribooms": ".post-content > pre:nth-child(20)",
                        "#ar_padt": ".post-content > pre:nth-child(22)",
                        "#bg_btb": ".post-content > pre:nth-child(24)",
                        "#br_keb": ".post-content > pre:nth-child(26)",
                        "#bxr_bdt": ".post-content > pre:nth-child(28)",
                        "#ca_ancora": ".post-content > pre:nth-child(30)",
                        "#cs_cac": ".post-content > pre:nth-child(32)",
                        "#cs_fictree": ".post-content > pre:nth-child(34)",
                        "#cs_pdt": ".post-content > pre:nth-child(36)",
                        "#cs_pud": ".post-content > pre:nth-child(38)",
                        "#cu_proiel": ".post-content > pre:nth-child(40)",
                        "#da_ddt": ".post-content > pre:nth-child(42)",
                        "#de_gsd": ".post-content > pre:nth-child(44)",
                        "#el_gdt": ".post-content > pre:nth-child(46)",
                        "#en_ewt": ".post-content > pre:nth-child(48)",
                        "#en_gum": ".post-content > pre:nth-child(50)",
                        "#en_lines": ".post-content > pre:nth-child(52)",
                        "#en_pud": ".post-content > pre:nth-child(54)",
                        "#es_ancora": ".post-content > pre:nth-child(56)",
                        "#et_edt": ".post-content > pre:nth-child(58)",
                        "#eu_bdt": ".post-content > pre:nth-child(60)",
                        "#fa_seraji": ".post-content > pre:nth-child(62)",
                        "#fi_ftb": ".post-content > pre:nth-child(64)",
                        "#fi_pud": ".post-content > pre:nth-child(66)",
                        "#fi_tdt": ".post-content > pre:nth-child(68)",
                        "#fo_oft": ".post-content > pre:nth-child(70)",
                        "#fr_gsd": ".post-content > pre:nth-child(72)",
                        "#fr_sequoia": ".post-content > pre:nth-child(74)",
                        "#fr_spoken": ".post-content > pre:nth-child(76)",
                        "#fro_srcmf": ".post-content > pre:nth-child(78)",
                        "#ga_idt": ".post-content > pre:nth-child(80)",
                        "#gl_ctg": ".post-content > pre:nth-child(82)",
                        "#gl_treegal": ".post-content > pre:nth-child(84)",
                        "#got_proiel": ".post-content > pre:nth-child(86)",
                        "#grc_perseus": ".post-content > pre:nth-child(88)",
                        "#grc_proiel": ".post-content > pre:nth-child(90)",
                        "#he_htb": ".post-content > pre:nth-child(92)",
                        "#hi_hdtb": ".post-content > pre:nth-child(94)",
                        "#hr_set": ".post-content > pre:nth-child(96)",
                        "#hsb_ufal": ".post-content > pre:nth-child(98)",
                        "#hu_szeged": ".post-content > pre:nth-child(100)",
                        "#hy_armtdp": ".post-content > pre:nth-child(102)",
                        "#id_gsd": ".post-content > pre:nth-child(104)",
                        "#it_isdt": ".post-content > pre:nth-child(106)",
                        "#it_postwita": ".post-content > pre:nth-child(108)",
                        "#ja_gsd": ".post-content > pre:nth-child(110)",
                        "#ja_modern": ".post-content > pre:nth-child(112)",
                        "#kk_ktb": ".post-content > pre:nth-child(114)",
                        "#kmr_mg": ".post-content > pre:nth-child(116)",
                        "#ko_gsd": ".post-content > pre:nth-child(118)",
                        "#ko_kaist": ".post-content > pre:nth-child(120)",
                        "#la_ittb": ".post-content > pre:nth-child(122)",
                        "#la_perseus": ".post-content > pre:nth-child(124)",
                        "#la_proiel": ".post-content > pre:nth-child(126)",
                        "#lv_lvtb": ".post-content > pre:nth-child(128)",
                        "#nl_alpino": ".post-content > pre:nth-child(130)",
                        "#nl_lassysmall": ".post-content > pre:nth-child(132)",
                        "#no_bokmaal": ".post-content > pre:nth-child(134)",
                        "#no_nynorsk": ".post-content > pre:nth-child(136)",
                        "#no_nynorsklia": ".post-content > pre:nth-child(138)",
                        "#pcm_nsc": ".post-content > pre:nth-child(140)",
                        "#pl_lfg": ".post-content > pre:nth-child(142)",
                        "#pl_sz": ".post-content > pre:nth-child(144)",
                        "#pt_bosque": ".post-content > pre:nth-child(146)",
                        "#ro_rrt": ".post-content > pre:nth-child(148)",
                        "#ru_syntagrus": ".post-content > pre:nth-child(150)",
                        "#ru_taiga": ".post-content > pre:nth-child(152)",
                        "#sk_snk": ".post-content > pre:nth-child(154)",
                        "#sl_ssj": ".post-content > pre:nth-child(156)",
                        "#sl_sst": ".post-content > pre:nth-child(158)",
                        "#sme_giella": ".post-content > pre:nth-child(160)",
                        "#sr_set": ".post-content > pre:nth-child(162)",
                        "#sv_lines": ".post-content > pre:nth-child(164)",
                        "#sv_pud": ".post-content > pre:nth-child(166)",
                        "#sv_talbanken": ".post-content > pre:nth-child(168)",
                        "#th_pud": ".post-content > pre:nth-child(170)",
                        "#tr_imst": ".post-content > pre:nth-child(172)",
                        "#ug_udt": ".post-content > pre:nth-child(174)",
                        "#uk_iu": ".post-content > pre:nth-child(176)",
                        "#ur_udtb": ".post-content > pre:nth-child(178)",
                        "#vi_vtb": ".post-content > pre:nth-child(180)",
                        "#zh_gsd": ".post-content > pre:nth-child(182)"}

SECTION_DETAILS = {"group": TREEBANK_GROUPS, "individual": INDIVIDUAL_TREEBANKS}

RESULTS_TYPES = ['las', 'mlas', 'blex', 'uas', 'clas', 'upos', 'xpos', 'ufeats', 'alltags', 'lemmas', 'sentences', 'words', 'tokens']

RESULTS_TYPES_NAMES = {'las': "Labeled Attachment Score (LAS)", 'mlas': "Morphology-Aware Labeled Attachment Score (MLAS)",
                       'blex': "Bilexical dependency score (BLEX)", 'uas': "UAS", 'clas': "CLAS", 'upos': "UPOS tagging",
                       'xpos': "XPOS tagging", 'ufeats': "Morphological features", 'alltags': "All morphological tags",
                       'lemmas': "Lemmatization", 'sentences': "Sentence segmentation", 'words': "Word segmentation",
                       'tokens': "Tokenization"}

SECTION_TYPES = ["group", "individual"]
